# Generated by Django 3.0.7 on 2020-06-23 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, upload_to='directory/static/avatars')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{2,3} [\\d ]{9,15}$', message="Phone number must be entered in the format: '+971 55 555 5555'.")])),
                ('room', models.IntegerField()),
                ('subjects', models.ManyToManyField(to='directory.Subject')),
            ],
        ),
    ]
